### ISSUE TITLE
Column header icon in TB 91

### ISSUE THREAD

**Issue by DenB10** [mlazdans/qnote#14]
Another issue with Thunderbird 91: the column header icon in the message list does not appear.

**Comment by DenB10** [comment]
Of course.
![Presse-papiers-1](https://user-images.githubusercontent.com/9309147/137599801-40245a93-1574-4801-8bc9-24cc5c3b07dd.png)

**Comment by mlazdans** [comment]
Oh, I see :) Was looking in wrong direction.
