### ISSUE TITLE
Q-Note window in white black

### ISSUE THREAD

**Issue by Bajueha** [mlazdans/qnote#17]
Hello, I am using WIN 10 21H1, TB 91.2.0 (64-bit) and Q-Note 0.10.4.
Windows is running in "Dark Mode" and in TB the theme "System Theme" is active.
Recently I did TB upgrade 78.xx to 91.2.0. Until 78.xx Q-Note worked fine. After that, now the note window is divided only white-black, and the text is displayed black, runs when writing in the sharp area of the window, which becomes white under the text : 
picture 1
If I change the TB theme to "Light", the window becomes white-yellow, the text is also displayed black, runs into the yellow area of the window, which then becomes white under the text : picture 2
Until TB 78.xx also the note window under the mail header was yellow, now unfortunately also only black with white text : picture 3
Martins, maybe you have an explanation why this could be ?
Many thanks in advance
![picture_2](https://user-images.githubusercontent.com/92805976/137939951-a1d872dc-acec-4a77-947d-25fb0f037aa0.PNG)
![picture_3](https://user-images.githubusercontent.com/92805976/137939952-5373558c-5218-413f-87d3-3e1a7e709d60.PNG)
![picture_1](https://user-images.githubusercontent.com/92805976/137939955-e63ad60e-6256-4cd5-a36c-88e1dffd2d69.PNG)
.

**Comment by mlazdans** [comment]
Sure, no worries. Take your time. You can view console with cntrl+shift+j or tools->developer tools->developer toolbox

**Comment by mlazdans** [comment]
I haven't received any emails. Hard to tell from these messages, most are unreadable. Some messages about profile folder... Can you open your profile folder? Help -> More trouble shoot -> and click Open next to Profile Folder

Are you using some custom theme?

**Comment by Bajueha** [comment]
Hello Martins, unfortunately I only got around to answering today. I was able to solve the problem in the form that I have created a new profile, and in it now use a combination of two different themes. Once the default theme "Light" and additionally the theme "Grubov Dark". With this, it now works as desired and also the "Notes" look as they should. Thanks again for the support.

**Comment by mlazdans** [comment]
Great :)

**Comment by Bajueha** [comment]
Thanks again for the support. Further all the best for you and "QNote".

**Comment by mlazdans** [comment]
Btw, could you please post a link where I can get this Grubov Dark theme? Thanks!

**Comment by Bajueha** [comment]
Hi Martins, sorry, that was a typo of mine, the theme is correctly called "Gruvbox Dark" and was found in Thunderbird via Themes. Now, for whatever reason, no longer. But here you should find it : https://addons.mozilla.org/de/firefox/addon/gruvbox-dark-theme/

**Comment by Bajueha** [comment]
Relatively also here : https://github.com/morhetz/gruvbox

**Comment by mlazdans** [comment]
Added this theme to my dev environment but can't replicate...
