### ISSUE TITLE
QNote clashes with Nostalgy++ 

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [mlazdans/qnote#18]
After upgrading to TB 91 I cannot use QNote together with Nostalgy++ 3.0.4 (https://addons.thunderbird.net/de/thunderbird/addon/nostalgy_ng/) any more. It worked without any problem with TB 78.
While typing a QNote, Nostalgy++ recognizes the keystrokes typed into the note as commands, opens its configuration window and all sorts of funny things. 
This did not happen with TB 78 (using the same Nostalgy++ 3.0.4 version). It also does not happen when I write a normal email.
I guess QNote keystrokes before were recognized as "normal email keystrokes" while now they are recognized as keystrokes "outside any mail" and thus triggering Nostalgy++.
Can you help?

**Comment by mlazdans** [comment]
Simple patch has been [submitted](https://github.com/opto/nostalgy-xpi/issues/128#issuecomment-1100380599).
