### ISSUE TITLE
Notes are not writable

### ISSUE THREAD

**Issue by nobswolf** [mlazdans/qnote#19]
I had this problem:
When opening a new note, the window appears, but it behaves "static". It does not get the keyboard focus.

This just did "vanish". I did not change anything, but now the Qnotes do get a focus and I can type.

But now the Qnotes are not movable and not resizable.

Version of TB: 91.3.0 (64-Bit) running on Debian 10 with XFCE

Version of Qnotes: 0.10.4 

I tried a new installation of Qnotes. This did not change anything

**Comment by mlazdans** [comment]
Can't reproduce on my Ubuntu Linux and TB91.3

Please restart TB and send a screenshot of error console.

**Comment by nobswolf** [comment]
I select a message, click button of Qnote, then the first lines appear, no lines when trying to move the Qnote

08:30:25.757 messageDisplayAction.onClicked() background.js:210:17
08:30:25.757 QNotePopToggle(), popupId = -not set- utils.js:347:17
08:30:25.761 XULNoteWindow.persistAndClose() - closing... NoteWindow.js:150:18
08:30:25.761 XULNoteWindow.persistAndClose() - not shown! NoteWindow.js:153:19
08:30:25.764 createNote(re-pX7f5LCpifnepugaGwg-4P12CESV-4OYXXHMI-EW319TD@news.metro24.de) utils-note.js:2:16
08:30:25.765 XULNoteWindow.pop() - popping... NoteWindow.js:183:18
08:30:25.770 WebExtensions: qpopup.create() qpopup.js:179
08:30:25.783 QNotePopToggle(), isPopped = 
Object { anchor: "message", anchorPlacement: "center", focused: null, height: 200, id: 6, left: 1548, offsetLeft: null, offsetTop: null, top: 821, width: 300, … }
utils.js:349:18
08:30:25.794 WebExtensions: qapp.attachNoteToMessage(3) qapp.js:576
08:30:25.795 WebExtensions: qapp.attachNoteToMessage(3) - note doest no exist qapp.js:586

then I select another message and back into the one with the Qnote:

08:31:08.236 messageDisplay.onMessageDisplayed(), messageId: 1 background.js:177:17
08:31:08.236 XULNoteWindow.persistAndClose() - closing... NoteWindow.js:150:18
08:31:08.236 XULNoteWindow.persistAndClose() - not shown! NoteWindow.js:153:19
08:31:08.249 createNote(re-pX7f5LCpifnepugaGwg-4P12CESV-4OYXXHMI-EW319TD@news.metro24.de) utils-note.js:2:16
08:31:08.252 XULNoteWindow.pop() - popping... NoteWindow.js:183:18
08:31:08.277 Das Cookie "" wurde als Drittanbieter abgelehnt. fonts.css
08:31:08.280 WebExtensions: qpopup.create() qpopup.js:179
08:31:08.296 Das Cookie "" wurde als Drittanbieter abgelehnt. 4P12CESV-4OYXXHMI-6JAPJW.gif
08:31:08.318 GEThttps://news.metro24.de/op/12/4P12CESV-4OYXXHMI-6JAPJW.gif
[HTTP/1.1 200 OK 1023ms]

08:31:08.345 WebExtensions: qapp.attachNoteToMessage(3) qapp.js:576
08:31:08.356 GEThttps://news.metro24.de/assets/bm/ostatic/metro/profiTipp/fonts/fonts.css
[HTTP/1.1 200 OK 0ms]

again no additional lines when trying to move the Qnote

**Comment by nobswolf** [comment]
I just disabled all the other add-ons: No change, Qnotes are still not movable.

**Comment by nobswolf** [comment]
I think I tracked it down: I use movemail and some configuratons are stored in the directory of the movemail-account...

TB kicked movemail and so did break a lot of other things :-/ 

https://bugzilla.mozilla.org/show_bug.cgi?id=1625741

**Comment by mlazdans** [comment]
I'm glad you found the core of the issue. It's really annoying after all these changes and bugs they are making at TB :(
