### ISSUE TITLE
Strange behavior ot the toolbar icon

### ISSUE THREAD

**Issue by DenB10** [mlazdans/qnote#2]
I'm running Thunderbird 78.5.0 64-bit on Win7 64-bit.

- I create a new note.
- I save and close the note: the icon becomes colored.
- I click on the toolbar button, the note reappears but the icon becomes grey.
- I close the note again, the icon remains grey.
- Clicking the toolbar button toggles the note and the icon still remains grey.
- I select another message and come back on the one with the note: the note appears and the toolbar icon is colored as expected.

I think this is an issue introduced in version 0.9 since there was no problem with the version 0.7!

**Comment by mlazdans** [comment]
Will be fixed in next release
