### ISSUE TITLE
Add clickable hyperlinks

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [mlazdans/qnote#22]
Sometimes I add links to QNote text. 
Would be useful if I could click on those links to open the corresponding page.
Currently they are rendered as normal text (see the two links below), so that I have to copy/paste to open the page.
![Issue #18](https://user-images.githubusercontent.com/8068047/151788220-2ba2a4aa-4951-4240-a52f-116dd0325021.png)

**Comment by mlazdans** [comment]
QNote usis simple textarea HTML element. Adding clickable hyperlinks will bloat this extensions, so will mark as wont fix. Sorry.
