### ISSUE TITLE
NOT WORKING with TB 102 Beta 1

### ISSUE THREAD

**Issue by julienmueller** [mlazdans/qnote#25]
AddOn is **no longer functional** with the current **Thunderbird 102 Beta 1** . I tried disabling compatibility check, which re-actives the extension. Unfortunately clicking the QNote buttons in the interface has no effect.
Could you please adapt it to the latest generation of TB? It would be much appreciated. Thanks.

**Comment by mlazdans** [comment]
It is not that QNote is broken, but rather they broke extensions API (again) somewhere around TB100 beta/alpha :rage:  :-1:

I will investigate in some spare time.

**Comment by peci1** [comment]
I've tried current master branch and it seems to work well with TB 102! Thanks!

**Comment by mlazdans** [comment]
Thanks for taking a look and testing. I will soon push it to thunderbird.net :)
