### ISSUE TITLE
Searching Qnotes in QuickFilter will exclude emails matching the Subject, Body, Sender, etc. in some cases 

### ISSUE THREAD

**Issue by kings2u** [mlazdans/qnote#28]
First, THANK YOU for this extension!

I use Thunderbird's QuickFilter all the time to search emails, and I value Qnotes ability to add searchable text to emails that otherwise wouldn’t use a keyword. This works in most cases, except when I’m using QuickFilter to search two or more words that aren’t in quotes. In that case, I will get appropriate "fuzzy" matches if I don’t use Qnotes in the QuickFilter settings, but when I use Qnotes, I don’t get any matches for a multi-word search unless the words are in quotes for an exact match. 

Is it possible to get fuzzy matches using Qnotes in the QuickFilter?

**Comment by mlazdans** [comment]
Please give an example. I haven't noticed fuzzy matching with QuickFilter. What version do you use?

**Comment by mlazdans** [comment]
No feedback
