### ISSUE TITLE
Note stay open if I close thunderbird Window

### ISSUE THREAD

**Issue by PHIL-IP** [mlazdans/qnote#29]
First I use TBTray to disable closing Thunderbird.
1 - Create a new note on a message
2 - When I reduce Thunderbird using **_** or **X** buttons then the window of the note stay on screen (wihtout Thunderbird)

Is there a way to hide the window when Thunderbird is "closed" using the X button (not really closed ;) ) ?

**Comment by mlazdans** [comment]
Minimizing with native TB works fine. Probably issue is more related to TBTray not QNote or Thunderbird.

**Comment by ErikKrause** [comment]
This still happens when regularly closing thunderbird and note is"own window". Also if thunderbird is minimized.
Thunderbird 102.5.1 (32-Bit) on Windows 10 pro
