### ISSUE TITLE
About date formatting in the future version 0.9.2

### ISSUE THREAD

**Issue by DenB10** [mlazdans/qnote#3]
I'm testing your last version of QNote (0.9.2?).
Besides welcome options like the default placement of the note or the delete confirmation, there is a new option to format the date.
This would be nice but, as the used method doesn't support locales, it's not possible to have the date in the locale if you include the weekday or the month name for example.
In my opinion, this is a problem. I'm not a developer but is there another formatting method which supports locales?

**Comment by mlazdans** [comment]
Currently date formatting is dependent on this [implementation](https://locutus.io/php/datetime/date/). Adding locale support for dates requires coding. I can't be done by simple translation. Any suggestion of ready-to-go implementation?

**Comment by DenB10** [comment]
Unfortunately no. As I said it above, I'm not a developer and I have no idea about coding.
So you know I have no suggestion for a ready-to-go solution!!!

Does "your" implementation exist in an extended "localized" version? Or, is it possible to join one?

And the method "Date.toLocaleString()" that I find in some mozilla extensions? Maybe with less choice for the parameters in the format?

Sorry but I am unaware.

**Comment by mlazdans** [comment]
Currently I'm not aware of good localized date formatting solution. Built in Intl.DateTimeFormat() is rather limited.

Default toLocaleString() will be used when you leave date format option empty. I should probably add locale string to it though.

**Comment by DenB10** [comment]
My final opinion is  this option which intends to customize the date format is not very necessary: the old format was good enough.
Maybe, it's better to work on how to retrieve the search function?

But this is my own opinion!

**Comment by mlazdans** [comment]
You will get that if you leave dateFormat option empty. I started to play with localized dates, seems promising. Are you willing to become a beta tester perhaps?

Regarding search: there are some TB internals I can't go around currently, but this will be the next big thing I'm gonna dive in.

**Comment by DenB10** [comment]
Because of the restrictions due to the pandemic in France, I have some free time to help you testing if you want, no problem!

**Comment by mlazdans** [comment]
Great! Please send me a msg to qnote@dqdp.net and I will add you to the beta testers list.

**Comment by mlazdans** [comment]
Fixed in next release.
