### ISSUE TITLE
feature request: sync oder clients by imap fodler

### ISSUE THREAD

**Issue by olafsosath** [mlazdans/qnote#31]
I would like to suggest the following feature:
Store qnotes in special imap folder.
This feature would enable users to use qnote-Plugin continuously over different clients - e.g. work and home client.

**Comment by mlazdans** [comment]
You can share .qnote files using Dropbox or similar file sharing technology.

Implementing IMAP client in webextension won't be easy. If you know ready-to-go implementation please let me know.
