### ISSUE TITLE
Future version 0.12: Truncated options page

### ISSUE THREAD

**Issue by DenB10** [mlazdans/qnote#33]
Hello,
I am testing the future version of QNote and I notice a bug in the display of options, not all options are displayed when you open the options page. Can you reproduce it?

**Comment by mlazdans** [comment]
Please add screenshot

**Comment by DenB10** [comment]
When opening options page:
![Presse-papiers-1](https://user-images.githubusercontent.com/9309147/201317281-411c6c9a-8d6e-412d-9da9-55349a9f0958.png)

By clicking on the wrench icon or by calling up the options from the context menu:
![Presse-papiers-2](https://user-images.githubusercontent.com/9309147/201318583-f1af07fe-c793-4268-bc4f-52415658a707.png)

**Comment by DenB10** [comment]
Weird, I have to add "min-height: 1300px;" in "body" in options.css to have no more problem. ?????

**Comment by mlazdans** [comment]
Please try this version: https://files.fm/u/8myx6ctrc
This should fix options page. I also updated FR locale.

Btw on what TB version you got this issue?

**Comment by DenB10** [comment]
Sorry for the late reply.
OK, the issue is gone now, thanks. It seems 'messenger.css' was too much!
I am currently using Thunderbird version 102.4.1 (soon 102.4.2 but I think it won't change anything).
