### ISSUE TITLE
feature request: date and text in one line

### ISSUE THREAD

**Issue by ErikKrause** [mlazdans/qnote#34]
I can choose whether I want to attach title and / or text to the message. Both of them occupy more than a line. If I choose to not display the title (to save screen space) I don't see the date anymore. Would it be possible to only display the date and text - preferable in one line?

**Comment by mlazdans** [comment]
This gave me an idea about introducing templating. Would be more versatile. Hmm...

**Comment by mlazdans** [comment]
You can now adjust this using template support added in version 0.13.0
