### ISSUE TITLE
feature request: display on hover column icon

### ISSUE THREAD

**Issue by ErikKrause** [mlazdans/qnote#36]
Hello,
I don't know whether this would be possible, but a nice feature would be to show the note popup hovering the icon in the qnote column without clicking the actual message.
Edit: 
I just discovered, that the first characters of the note are displayed in the note column. So this might be less important. However, displaying the whole note (or some more characters) onhover would still be nice.

**Comment by mlazdans** [comment]
I've tried earlier this but could not find a good solution. Seems TB itself manages mouse over column actions.  For example TB shows some title/balloon on mouse over when shrinking windows so that columns get compressed.

**Comment by mlazdans** [comment]
For now you can use hack: in preferences  set show first X characters to a large value and TB will show a title when mouse over.

**Comment by ErikKrause** [comment]
> For now you can use hack: in preferences set show first X characters to a large value and TB will show a title when mouse over.

This didn't work when I first tried, but then I realized, that I need to widen the column a bit until at least `...` is shown. Many thanks!
