### ISSUE TITLE
Thunderbird crashes when opening mails with qnote in Linux

### ISSUE THREAD

**Issue by janstarke** [mlazdans/qnote#37]
Hi,

I'm using qnote in Thunderbird on Linux as well as Windows. Since some time (don't know exactly when), Thunderbird crashes when I open a mail to which I have attached a qnote. This happens only on the Linux machine, but not on the Windows machine

# Used Environment

QNote: 0.12.2
Thunderbird: 102.4.2 (64bit)
Operating System: Ubuntu Linux 22.04.1 LTS

Is this a known problem? Do you need any more information to troubleshoot this issue?

Regards, Jan

**Comment by mlazdans** [comment]
Any logfiles could be helpful. Anything in /var/log/ log files perhaps? Or generated [crash report](https://support.mozilla.org/en-US/kb/mozilla-crash-reporter-tb)?

**Comment by janstarke** [comment]
There are no OS logs, and the crash report files do only contain a report id. Can I get the real content from somewhere?

I also tried to enable the error console before clicking on "QNote", but this windows also crashes immediately, so I cannot provide more information. Is it possible to extract some error log directly from QNote?

**Comment by mlazdans** [comment]
No there are no special qnote logs. Can you check your storage folder if it is accessible with user you running TB? Any fancy characters there in path? Can you update TB to the latest?

**Comment by mlazdans** [comment]
Closed due no input
