### ISSUE TITLE
Longer lines in header notes should wrap around

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [mlazdans/qnote#39]
When I write in QNote a line longer than the current window size of my mail text window it is not wrapped around at the end of the window but is creating a scrollbar which is not convenient to read.
Thunderbird does wrap around any longer lines of the mail text itself automatically.
![Issue, QNote not wrapped](https://user-images.githubusercontent.com/8068047/214564023-c7d2fb56-9a1b-4216-8bab-00eb5543197e.jpg)

I need to scroll to the right to be able to read the rest of the longer QNote line:
![Issue, QNote not wrapped, right side](https://user-images.githubusercontent.com/8068047/214564092-4f8bb688-9f63-48ed-830a-d1508a69ecc0.jpg)

**Comment by ThomasHeinrichSchmidt** [comment]
Am I all alone here? No one but me has the problem?

**Comment by mlazdans** [comment]
Not necessary :) I think I saw this too. Will take a look around next release.
