### ISSUE TITLE
IMAP and multiple Users in one Account

### ISSUE THREAD

**Issue by ow8m8laune** [mlazdans/qnote#4]
Hey everyone,
I'm actually asking for help because i think it would be nice to have for sure!

Is it possible to store **notes** information in an external file (stored on NAS-Server for example or on imap server directly) and get those information into Thunderbird? I'm working with a small team & with thunderbird.. and notes inside those emails would be great to work with.

**Comment by mlazdans** [comment]
Hello!

You can configure QNote to store notes into folder. And then you can mount that folder as you wish - network share, NFS, DropBox, etc. Hope that helps?

Storing into IMAP is technically possible (or to be more specific - storing inside message headers) but rather cumbersome. I did not find a good IMAP/headers handling library for TB but there are some very low level functions to do that. However implementing this feature from such low level potentially would open a whole lot of can of bugs. Not sure I wanna go down that rabbit hole and not sure if that's even worth it :)
