### ISSUE TITLE
Alt + Q shortcut should set focus on the note popup

### ISSUE THREAD

**Issue by sebthemagnificient** [mlazdans/qnote#42]
Hello,

This is not really a bug report but more of an upgrade suggestion. 

Alt + Q shortcut is great but could be a lot greater if the qnote's popup could receive the focus on the go. The user could then avoid the pain of using the mouse to set the focus himself.
Other avoided mistake's example : as your first note's letter is a A, and you did not notice that the note was not focused, you archived a mail and probably will struggle to find it again!

The result would be Alt + Q (open note and focus it) → write your note → Alt + Q (close the note)

Thank you for this extension, i use it everyday

**Comment by mlazdans** [comment]
Hi!

Do you have "Focus QNote after display" enabled in settings?

**Comment by sebthemagnificient** [comment]
<img src="https://media.tenor.com/7kAd9XNcHnYAAAAM/hello-mcfly.gif" alt="what an idiot i am!" />

...thank you, the translation is so good that i did not manage to understand it..

Everything is now perfect, sorry for hopening this issue before a double check...
