### ISSUE TITLE
no longer compatible with TH 115

### ISSUE THREAD

**Issue by IT-Mpdl** [mlazdans/qnote#45]
just updated to the new TH. Ver. 115.0, and the addon is no longer compatible. Will it be updated? 

Thank you.

**Comment by mlazdans** [comment]
Updated so that it works with TB115 but not completely. Column handler won't work. They changed TB so much that it is not possible to create columns at the moment. QuickFilter also does not work fully so it is disabled for now.

**Comment by maidstein** [comment]
After 1.5 months since your last update, I just wanted to ask if you are still working on a solution to the column handler problem. 
I would donate for a relatively quick fix!
Thank you!

**Comment by mlazdans** [comment]
Column handler won't work. They changed TB so much that it is not possible to create columns at the moment. Sorry. If you know the solution I would be happy to take a look.

**Comment by maidstein** [comment]
That's very sad. Unfortunately, I have no programming experience at all.
Is there anyone who can help get QNote fully working again under TB 115 (Supernova) again?
In particular, it is about displaying the notes in a column of the email list. It's not necessary to display a text excerpt from the note in this column.
Anyone?

**Comment by mlazdans** [comment]
For now I'm just keep using 102. They broke so many things and this 115 is not worth it IMO.

**Comment by mlazdans** [comment]
This worked for me to downgrade TB115 to TB102:
`thunderbird -profilemanager --allow-downgrade`

**Comment by Soluclim** [comment]
Hi, Anybody can explain to me how to donwgrade under Win11 ?
I'm not used to windows...
Thanks to mlazdans for all his job !

**Comment by mlazdans** [comment]
Not 100% sure, but should be similar. You have to find installation folder and then run cmd.exe in it and execute
`thunderbird.exe -profilemanager --allow-downgrade` command.

If TB is installed via MS Store then it is a different procedure probably. I'm on Win10.

**Comment by Soluclim** [comment]
I don't hundstand how to downgrade. What ever I will run under TB115 waiting for ... or adapt me ! Thanks.

**Comment by maxnikulin** [comment]
> Column handler won't work. They changed TB so much that it is not possible to create columns at the moment. Sorry. If you know the solution I would be happy to take a look.

See [Bug #1817682 No way for extensions to add columns to the new tree list widgets](https://bugzilla.mozilla.org/1817682). Custom columns are possible in Thunderbird-115.10.

I am not a qnote user. Earlier your code helped me to create my own add-on, so the project was starting point when I was exploring feasibility of custom columns in current ESR version.

**Comment by mlazdans** [comment]
Latest release is now compatible with TB115 and TB128

**Comment by maidstein** [comment]
Thank you so much, @mlazdans !
