### ISSUE TITLE
Mail overview column (Spalte Mailübersicht)

### ISSUE THREAD

**Issue by B-Gruen** [mlazdans/qnote#46]
In the mail overview no column for QNote can be set up, so a sorting function is also missing.
In the (advanced) search the column is available, but can not be sorted either. 

--------

In der Mailübersicht kann keine Spalte für QNote eingerichtet werden, also fehlt auch eine Sortierfunktion.
In der (erweiterten) Suche ist die Spalte vorhanden, lässt sich aber auch nicht sortieren. 

TB 115 | Windows 11

**Comment by mlazdans** [comment]
Please take a look:
https://github.com/mlazdans/qnote/issues/45#issuecomment-1660881810
https://github.com/mlazdans/qnote#known-issues
