### ISSUE TITLE
QNote compilation view

### ISSUE THREAD

**Issue by MAXXYM69** [mlazdans/qnote#47]
Ciao,
I wanted to ask if it was possible to return to this note compilation setting or to be able to select this setting(vers. 0.12.2)
![immagine](https://github.com/mlazdans/qnote/assets/144796241/c1e8a93e-668e-4fdf-99f5-9dc02df09b01)

or this compilation setting (vers. 0.12.3>5)
![immagine](https://github.com/mlazdans/qnote/assets/144796241/188749b7-571f-4463-91fa-cf8411bf3445)

Thank's
Max

**Comment by mlazdans** [comment]
Related to #34

**Comment by mlazdans** [comment]
You can now adjust this using template support added in version 0.13.0

**Comment by mlazdans** [comment]
Something like this should do the trick:
```
<div class="qnote-title">QNote: {{ qnote_date }}</div>
<div class="qnote-text"><pre class="moz-quote-pre" wrap="" style="margin: 0;">{{ qnote_text }}</pre></div>
```
