### ISSUE TITLE
Floating panel / Scrolling error - TH115

### ISSUE THREAD

**Issue by CHILIKE** [mlazdans/qnote#48]
**In case Floating panel > the content scrolling in the window does not work. (Win11 - TH 115.2.2 (64 bit))
!**

![qnfperror](https://github.com/mlazdans/qnote/assets/35606514/855a3b47-8f7c-4564-a330-31bef84099f7)

**Comment by mlazdans** [comment]
I can not replicate. Dod you tried on latest TB115?

**Comment by mlazdans** [comment]
Fix will be available in next release
