### ISSUE TITLE
Feature request: shareable notes with team members

### ISSUE THREAD

**Issue by thomas-trenz** [mlazdans/qnote#49]
My team of 5 uses the same E-Mail account, it@company.com. It would be great if one could add a note and all other members could then also see it. This could be done via a network share.

Regards,
Thomas

**Comment by MAXXYM69** [comment]
Basta creare una cartella condivisa dove QNote va a leggere
Questo, il mio settaggio per vedere la stessa nota nei vari pc che accedono alla mail
![immagine](https://github.com/mlazdans/qnote/assets/144796241/0a07677c-40f0-4965-a640-acc1859206dd)
