### ISSUE TITLE
Date and time formatting do not fully work.

### ISSUE THREAD

**Issue by Smutley** [mlazdans/qnote#50]
TBird 115.3.2
Windows 10 latest build
Latest Qnote

Date and time formatting do not fully work. For example: "h" should give 12 hour time with leading zeros; it shows up simply as the letter h (h:30 instead of 08:30 etc.). The same goes for "a" for lowercase am or pm. There are others that do not work.

**Comment by mlazdans** [comment]
Hello!

"h" and "a" are not (yet) implemented
![image](https://github.com/mlazdans/qnote/assets/48044624/32ec7dcf-0329-4b39-9511-46a7c28f656d)

Will see what can be done about it.

**Comment by mlazdans** [comment]
'aAghe' date formatting rules will be added in next release
