### ISSUE TITLE
Display not correct

### ISSUE THREAD

**Issue by jaryjaryJary** [mlazdans/qnote#51]
Hi, I am using the latest version of TB and have now installed xnote++. However, the display is not as I am used to from before. The unsightly grey bar at the top and the icons squeezed to the bottom are not really nice. Why do I see it like this and not like in your screenshots (dark yellow bar at the top)?
I can also no longer change the font size and the subject of the note. If I drag the note to another location, it does not stay there when I open it again. This used to be different.
![Thunderbird](https://github.com/mlazdans/qnote/assets/168303671/a5a7e1c7-54e3-48fc-8106-bb865a4849b0)

I am looking forward to your answer :-)
Kind Regards
Jary

**Comment by mlazdans** [comment]
This is not XNote support.
