### ISSUE TITLE
Feature reguest: Formatting of text

### ISSUE THREAD

**Issue by adambyw** [mlazdans/qnote#52]
I like your add-on very much. One thing that I find a bit missing and disturbing is the support of text formatting. And I don't even mean some styles which yes would be helpful, but would certainly complicate things.
Often when making notes in the editing window I use a new line, which is useful for noting down, for example, an address or a telephone number. And it shows up correctly in the editor window. But the same message in the window already appears on one line, which drastically reduces the readability of the note.
In html you would need to use the &lt;pre&gt; tag to solve this problem, or use the css property white-space: pre; 

![qnote](https://github.com/mlazdans/qnote/assets/45902774/038ddbad-82b0-46fa-9b4b-9128d54bcc9d)

**Comment by mlazdans** [comment]
Will make this configurable at some point because other users prefer current formatting.

**Comment by adambyw** [comment]
For those who would like to do this themselves, there is such an option.

In the profile directory, find or create the directory "chrome" and in it find or create the file userContent.css with the content:
`.qnote-text{
	white-space: pre;
}`
Then in thunderbird, open the "Settings Editor" and set the toolkit.legacyUserProfileCustomizations.stylesheets property to "true". Otherwise, the css file will not work.

**Comment by mlazdans** [comment]
Related to #34

**Comment by mlazdans** [comment]
You can now adjust this using template support added in version 0.13.0
