### ISSUE TITLE
Thunderbird 128 ESR support

### ISSUE THREAD

**Issue by GerryT11** [mlazdans/qnote#54]
Hi, the long-term release Thunderbird 128 ESR is out and QNote does not yet support it. Thanks.

**Comment by GerryT11** [comment]
There is a pull request for this bug/enhancement: https://github.com/mlazdans/qnote/pull/55

**Comment by JohnCbs** [comment]
I just changed "strict_max_version": "129.*" in the manifest

Works for me in 128 ESR. 
Minor GUI issues in the AddOn settings dialog regarding scrollbars and the textbox to enter storage path but still usable.

**Comment by mlazdans** [comment]
Soon will be release supporting (somewhat) TB115 and TB128

**Comment by pandyaph** [comment]
Hi team,
I have installed Qnote on my laptop. I am using Thunderbird 128.1.0esr (64-bit). Unfortunately notes are not visible on the message in thunderbird. I have tried all options. Please help.

**Comment by pandyaph** [comment]
Thanks. There is no error message. I just created note using add on but I
can't see the note pop up in message.
Prashant Pandya

**Comment by mlazdans** [comment]
Without console errors or anything I can't help much. Please check if storage path is correct and have appropriate permissions. Do you use Linux? Maybe related to https://github.com/mlazdans/qnote/issues/53#issuecomment-2211195997

**Comment by pandyaph** [comment]
Hi,
I am sorry I am not a technical guy so don't know how to see console.
Storage path should be correct. I am not using Linux. I am using Windows 10
Prashant Pandya

**Comment by mlazdans** [comment]
Press Tools -> Developers tools
![image](https://github.com/user-attachments/assets/6baa0322-fe7f-4c48-abd9-ccddf68c84a9)

**Comment by pandyaph** [comment]
Storage path is C:\Users\Acer\AppData\Roaming\Thunderbird\Profiles\0h40ae72.default-esr\QNote
Notes are saved in this location correctly. When I try to modify note it appears in message as per screen shot_01.
But in normal course it is not visible in message.
Attached is error seen in Error Console. (screen shot_02)
![Screenshot_1](https://github.com/user-attachments/assets/86485dff-c947-4dbc-9b9c-b9547278b6a6)
![Screenshot_2](https://github.com/user-attachments/assets/0af72584-cbdc-4be6-91e8-81289a1950bb)

**Comment by mlazdans** [comment]
So then what is the problem again? What you mean by "But in normal course it is not visible in message."?

**Comment by mlazdans** [comment]
Can you send full console log? Left click on console log and save all messages to file
![image](https://github.com/user-attachments/assets/3fe1c3f7-20e4-43ee-a125-78ddaa06afb7)

**Comment by pandyaph** [comment]
I can't see Note on message. I was able to see the note when I select the message in XNote. In this add on I am not able to see the note while going to the message

**Comment by pandyaph** [comment]
Here is full console log.
[console-export-2024-8-19_19-23-10.txt](https://github.com/user-attachments/files/16661131/console-export-2024-8-19_19-23-10.txt)

**Comment by mlazdans** [comment]
I'm not sure what you mean by "Note on message". Previously you showed screenshot with note.

Did you enable "show popup on message selection" in options?
![image](https://github.com/user-attachments/assets/838394a1-750c-4595-a0d8-b2e33989a337)

Or maybe attach note to message?
![image](https://github.com/user-attachments/assets/09d0bdf1-b24d-4bac-9610-4f5196710c8a)

**Comment by pandyaph** [comment]
Yes I have enable "show popup on message selection" in options. Earlier I sent you screen shot which was taken while Modifying note. I am sending you two screeshots again. When I modify the note then only it appears on message. When I select the message or message header the note should appear there.

![Screenshot_1](https://github.com/user-attachments/assets/ec818522-9966-47a9-a708-507f722249ed)
![Screenshot_2](https://github.com/user-attachments/assets/9f17cd45-3925-414d-9144-d87e6c6b3af9)

**Comment by pandyaph** [comment]
Yes I use many extensions. I tried to change theme but there is no change in layout.

**Comment by mlazdans** [comment]
I do not know what layout is that. And not sure if I want to support non standart layouts. Can you please send trouble shoot information (privately to qnote@dqdp.net) and will see. 
![image](https://github.com/user-attachments/assets/fe9ed200-5332-4156-afe1-9963553b8de6)

Meanwhile I will close this issue.

**Comment by mlazdans** [comment]
TB128 was added in latest release. Non standart layouts not supported yet.
