### ISSUE TITLE
Note Popup empty (Thunderbird 128.1.0esr 64-Bit on macOS 14.6.1)

### ISSUE THREAD

**Issue by alexanderzeh** [mlazdans/qnote#58]
Hey,
as the titel says, the note popup (doesn't matter if opened via button or option + q shortcut) is empty. The popup works, when I type and click at the right position where the icons for save&close or delete should be. The note itself shows up in the message view as well. But of course that's not really usable as I also can't see the text I'm typing.
In this case the console doesn't show anything.

When I change the setting from "post-it" to "own window" (sorry if that's not the correct name, as I'm using the german version and I'm translating it to what I _think_ might be the english name in the setting.) the popup doesn't show up . There's just a short flicker of a popup. 
The following errors show up in the console then:
![error console](https://github.com/user-attachments/assets/1dc9cac2-e30d-4638-9000-23472851542f)

**Already mentioned in the title, but to be safe:**
TB Version: 128.1.0esr 64-Bit
OS: macOS 14.6.1 (ARM processor)
no other extensions installed, TB fresh install so the profile should be clean as well.

**Comment by mlazdans** [comment]
Please switch back to default floating panel and send some screenshots. I do not have a macs so I can't really test.

**Comment by alexanderzeh** [comment]
Unfortunately there's not much to see:
![empty_popup](https://github.com/user-attachments/assets/2ea70459-fbcb-4be0-bc55-6f0efffb244b)

If that helps, I'm willing to test

**Comment by mlazdans** [comment]
Very strange. Please try enabling debug messages in qnote settings, restart TB, try create new note (so that this blank window appears) and then send me all console messages to qnote@dqdp.net (as attachment)? Right click in console, 'save all messages'
![image](https://github.com/user-attachments/assets/0b748292-c2ba-4f42-ba74-4218d4231aa0)

**Comment by alexanderzeh** [comment]
I just sent you an email witht he console export.

**Comment by mlazdans** [comment]
Btw, did you use previous versions of QNote on same machine/OS and this issue appeared just recenlty or this is the first time?

**Comment by alexanderzeh** [comment]
Nope. The TB install is rather fresh. I just installed QNote for thefirst time and had the issue from the start.

**Comment by mlazdans** [comment]
Could be related to macOS in general. There was some complains before: https://github.com/mlazdans/qnote/issues/21

**Comment by alexanderzeh** [comment]
Unfortunately the mentioned workaround doesn't work in my case.
If I can help by testing something, please let me know.

**Comment by mlazdans** [comment]
Other window option is broken due to API changes. Will try to fix at some point

**Comment by alexanderzeh** [comment]
Thanks, I really appreciate your work.

**Comment by kumarpranay** [comment]
I am having exactly the same issue on MacOS.  I have been using the addon for a while and the issue just appeared after an update to thunderbird & qnote.  I am on:

MacOS 13.5.1
Thunderbird 128.1.1esr (64-bit)
QNote 0.13.0

**Comment by mlazdans** [comment]
Is anyone using MacOS willing to test white panel issue? Would probably need to set up a new TB profile so that testing will not interfere with main installation.

**Comment by alexanderzeh** [comment]
I‘d love to help, but I’m on vacation right now. I’m coming back in roughly a week. So I could test then. Maybe someone else can jump in. 🙂

**Comment by valentinmanescu** [comment]
> Is anyone using MacOS willing to tests white panel issue? Would probably need to set up a new TB profile so that testing will not interfere with main installation.

Hello,
I have the same problem and also I need to use your extension. 
Please give me an email (you can find it on my profile) with what you need in order to test.

Bellow you will find a screenshot.

<img width="1667" alt="Screenshot 2024-09-16 at 22 30 45" src="https://github.com/user-attachments/assets/9162ca49-42c3-4941-a9d1-054b2d378630">

Best regards,
Valentin

**Comment by AI4everr** [comment]
I’m facing the same issue. I’ve tried everything, including disabling other plugins and restarting, but nothing seems to work. Hopefully, someone can help.

**Comment by mlazdans** [comment]
Could please somebody try this development version? Is white panel still present? You can also try other Popup window option:
![image](https://github.com/user-attachments/assets/f5e07af8-534d-42d3-bd86-8a0af660b984)

This is development version. For now I strongly advise creating a new TB profile instead installing over existing version. Also: BACKUP NOTE FOLDER just in case!

[qnote-0.14.0pre1.xpi.zip](https://github.com/user-attachments/files/17058915/qnote-0.14.0pre1.xpi.zip)

**Comment by valentinmanescu** [comment]
Hello,
Is the same issue (I can type but I can't see what I type), I followed the next steps:
- I deleted the the last version
- I restarted TB version - 128.2.2esr (64-b
- I installed new version
- I restarted TB ti be sure.

Let me know if I can help with anything else or if I need to delete something manually.


<img width="1700" alt="Screenshot 2024-09-19 at 15 32 14" src="https://github.com/user-attachments/assets/f25383ed-bf19-4ade-9a80-9faba2522adb">

**Comment by mlazdans** [comment]
Thanks for trying! So you can add notes with this blank screen? Can you blindly delete also? Click somewhere in the bottom left corner: 
![image](https://github.com/user-attachments/assets/5de3ff1d-46f4-43d2-bf59-3d71bd1d4ac5)

**Comment by valentinmanescu** [comment]
Hello,

I clicked in the bottom left corner and I can delete in blind.
Also I can select text from note, but it seems that I can add or delete text in blind.

Thanks for trying to fix the add-on, is very hard to work without it!

**Comment by AI4everr** [comment]
Correct, I experienced the same issue. You can type, but it’s essentially typing blind. I tried both the floating panel and popup panel options.

**Comment by mlazdans** [comment]
Feels like something does not get fully loaded. Something minor. Like .css. Scripts get loaded otherwise you won't be able to save or delete. I changed some paths, please try now?
[qnote-0.14.0pre2.xpi.zip](https://github.com/user-attachments/files/17059590/qnote-0.14.0pre2.xpi.zip)

**Comment by mlazdans** [comment]
If that still does not work here is another:
[qnote-0.14.0pre3.xpi.zip](https://github.com/user-attachments/files/17059626/qnote-0.14.0pre3.xpi.zip)

**Comment by valentinmanescu** [comment]
Is the same situation, if it helps please give me a mail (I posted on my profile) with your Whatsapp number and I can offer you acces by Anydesk on a MacOS laptop, with a fresh TB install.

Thanks!

**Comment by mlazdans** [comment]
This should be now fixed. Many thanks to @valentinmanescu for providing access to MacOS.

If anyone else wants to test out:
[qnote-0.14.0pre4.xpi.zip](https://github.com/user-attachments/files/17089543/qnote-0.14.0pre4.xpi.zip)
(please note it is still in dev mode)

**Comment by kumarpranay** [comment]
This is working but there are other issues with 0.14pre4. Not sure if I should put them here or wait for 0.14 official before making new tickets.

**Comment by mlazdans** [comment]
If it's related to blank panel, put them here, of course. If another issue, then create a new ticket please.
