### ISSUE TITLE
I can't dodation to you paypal account , thanks for QNote exteion

### ISSUE THREAD

**Issue by mean-cj** [mlazdans/qnote#59]
Hi @mlazdans 

Thank you so much for your QNote extension.
I don't know why; normally I can donate to others. , Please try changing to USD?

I can't donation to your paypal account. ^^
![image](https://github.com/user-attachments/assets/927dfe5f-f3b2-40a6-89d6-9b340bc842b5)

Regards

**Comment by mlazdans** [comment]
I believe this is Paypal issue. Thanks for trying 😊

**Comment by mlazdans** [comment]
Apparently one can create a new button with different currency. Please try: https://www.paypal.com/donate/?hosted_button_id=NKF22QJS87LWN
