### ISSUE TITLE
Strange QNote operation on some mails

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [mlazdans/qnote#6]
I have received an email that does behave strangely with QNote.
I successfully added a QNote to it but there is no note displayed until I press the `[QNote]` button in the tool bar. After that the correct note text is shown in a pop-up window and I'm able to edit it as normal.
But when I scroll through other emails in the summary and come back to this one email it again does not display the note until I press `[QNote]`.
I've generally set QNote to display existing notes not in a pop-up but below the mail header and this works fine, except for this one email where the QNote is not displayed until I press [QNote]- and then it's shown in a pop-up and not below the mail header as all the other QNotes.
I noticed one strange thing about the email in question, it's Message-ID is: `214656-350420841-1698522883@xsell.co`
while the corresponding note file's name is `14656-350420841-1698522883%40xsell.c.qnote`

It seems that Message-ID's for other emails are usually wrapped in angle brackets like this  `<8ab727c0-c9bd-43b1-6c4a-cfe8ed6c50e9@online.de>` where the corresponding note file's name then is `8ab727c0-c9bd-43b1-6c4a-cfe8ed6c50e9%40online.de.qnote`
I've searched through my email backup and found quite a number of emails (148 from a total of 46077 files, 0.3%) with no angle brackets on their Message-ID's (for searching I used the RegEx `"^Message-ID:[ ]+[^ <]"`).

Maybe QNote expects but does not check for the angle brackets? And then gets confused about Message-ID is like: `214656-350420841-1698522883@xsell.co` ?

**Comment by mlazdans** [comment]
Ah, actually I found a bug in add-on. Will be fixed in next release :facepalm:

**Comment by ThomasHeinrichSchmidt** [comment]
Version qnote-0.10.2.xpi was (automatically) installed today, but "strange operation" is still present.

**Comment by mlazdans** [comment]
Yes, this will be fixed in next release.
