### ISSUE TITLE
Temporary freezing of TB

### ISSUE THREAD

**Issue by B-Gruen** [mlazdans/qnote#60]
Hallo,

ich habe, nachdem ich hier gelesen habe, dass es eine Version von QNote dafür gibt, auf 128 gewechselt. Leider musste ich feststellen, dass der TB manchmal eine Kunstpause (Anzeige: " ..... Keine Rückmeldung") macht. Nachvollziehen kann ich das, indem einen beliebigen Ordner aus der Liste mit der rechten Maustaste angeklickt wird. Ist QNote deaktiviert, wird das gewünschte Fenster sofort angezeigt.

Danke und Grüße

-----------------------------

Hello,

after reading here that there is a version of QNote for this, I switched to 128. Unfortunately, I noticed that the TB sometimes pauses (display: ‘ ..... No response’). I can reproduce this by right-clicking on any folder in the list. If QNote is deactivated, the desired window is displayed immediately.

Thank you and best regards

https://www.thunderbird-mail.de/forum/thread/95215-qnote-in-128-mit-bug/

**Comment by mlazdans** [comment]
Can't reproduce on my machine. What's you TB version, QNote version and OS version? Or even better, please send troubleshoot information to qnote@dqdp.net
![image](https://github.com/user-attachments/assets/32625ce4-faa7-4aec-acae-c7fd8af9ea55)
