### ISSUE TITLE
Attached notes with all other email messages (QNote version 0.14.3)

### ISSUE THREAD

**Issue by pandyaph** [mlazdans/qnote#65]
Hi,
QNote version 0.14.3 is updated in my Laptop. I found one bug in it. The Last QNote created in Thunderbird is attached with all other email messages which are not attached with any note. Also if we open new tab then there also the last QNote is appearing.  Attached are the screenshots. Please resolve the issue.
![Screenshot_1](https://github.com/user-attachments/assets/b4fcbcf6-dddf-4f38-be9c-b5ccfa8d7f50)
![Screenshot_2](https://github.com/user-attachments/assets/74a317f9-ccfb-4d75-b510-4c19e1e9e55d)

**Comment by mlazdans** [comment]
Could you please check QNote folder for any .qnote (or .xnote) file without file name? Just blank .qnote (or .xnote) extension? 
Or find the file containing text from your screenshot?

**Comment by pandyaph** [comment]
Hi,
Sorry there is not file without file name. Attached is screenshot of files saved in QNote folder.
Regards,
Prashant
![Screenshot_1](https://github.com/user-attachments/assets/82d7f271-7ab8-46ba-b08b-c5e2478c4ced)

**Comment by mlazdans** [comment]
This is probably due to fact that you have selected one message with note in message pane. Probably switching tabs/windows triggers note to pop. Please try closing all notes and click on message that do not contain notes. Then click around tabs, etc. does note still pop?

**Comment by pandyaph** [comment]
Hi,
If I select the message without note then also the QNote of previous message pops up. I tried to close all Notes and tried again but still it pops up. Also tried to click on tab. On Tab also last QNote pops up.

**Comment by pandyaph** [comment]
I sent you email. I could not attach the file on this platform. Have you received my email ?

**Comment by pandyaph** [comment]
Hi,
Sorry I could not identify the file containing popping note text. Now I have deleted all the QNotes and created one new QNote for one email message. Now this QNote is popping up on all emails which are not having QNotes. Also it is popping up on Tab. I am attaching the zip file of QNote for your ready reference.
By the way in which program we can open the file ?
Regards,
Prashant
[CADutYQABP_3Dq_2ByLt2WZDg4BaFAq9h_zPw6oazW_3DHn6_3DUef7KcSA_40mail.gmail.com.zip](https://github.com/user-attachments/files/17296169/CADutYQABP_3Dq_2ByLt2WZDg4BaFAq9h_zPw6oazW_3DHn6_3DUef7KcSA_40mail.gmail.com.zip)

**Comment by mlazdans** [comment]
No, I did not receive email. You can open them in any text editor. Sorry, but I can't replicate this issue. Anything in error console perhaps?
![image](https://github.com/user-attachments/assets/45517604-b626-43ca-aa6b-f9e3ccc6b438)

**Comment by pandyaph** [comment]
Hi,
I tried to uninstall the QNote add on and reinstalled it but still the same problem. If I disable POP UP in Option 'Show popup on message selection' then popups are not appearing but If I enable it again last popup is showing on all messages which do not have QNote attached.

Here I am sending you few screenshots of Developer Toolbox and Error Console file. Will it be helpful to you ?

Thanks for your time.

Regards,

Prashant
[console-export-2024-10-9_9-48-58.txt](https://github.com/user-attachments/files/17301996/console-export-2024-10-9_9-48-58.txt)
![Screenshot_1](https://github.com/user-attachments/assets/bf707d5b-a026-495a-856d-518f8ad912ff)
![Screenshot_2](https://github.com/user-attachments/assets/cef513d3-0f6a-48de-92e7-5ef9ae1415b0)
![Screenshot_3](https://github.com/user-attachments/assets/5ff4479c-3496-43fe-81c9-03fcce6c1844)
![Screenshot_4](https://github.com/user-attachments/assets/7d7a43e5-3765-43ed-840a-1323e41926fa)

**Comment by mlazdans** [comment]
console-export-2024-10-9_9-48-58.txt is helpful, yes. Inspector screens are not needed.

From the log I only see one popup:
popNote(), keyId: **CADutYQAfGup-BoZVporiiSyBbQMtk80sLhqbkNgDyyghi-hhrw@mail.gmail.com** background.js:220:25

I see you clicked around but this is only one popup showing...

**Comment by pandyaph** [comment]
Hi,
Thanks. Yes only last QNote Pop up is interfearing with all other email messages. The last QNote Popup appears on all emails / tab etc even if Qnote is not attached with the email. There is no issue if the Popup is closed /disabled.
Regards,
Prashant

**Comment by mlazdans** [comment]
I got very confused about this report. So a popup does not pop on empty message, just stays open from previous message?

Popups does not close automatically anymore. It is now up to user to close with save, close w/o save or close with delete.

**Comment by pandyaph** [comment]
Sorry for the confusion. Yes popup of last email stays open on all other messages which do not have Qnote attached.
Yes I am closing the Popup with save but actually I want to keep the pop up open for all emails which are attached with Qnote.

**Comment by mlazdans** [comment]
I do not understand the problem anymore. I will close this now, please open new issue with clear description.

**Comment by pandyaph** [comment]
ok. Thanks for your time.

**Comment by pandyaph** [comment]
I made some changes in settings / options and now it is fine. Thanks
