### ISSUE TITLE
Word wrapping / line breaks

### ISSUE THREAD

**Issue by dompauling** [mlazdans/qnote#66]
Thank you so much for this add-on. It is really helpful.

But I am missing line breaks (they were possible in the early stage of the add-on, weren't they?).

I know that we can activate the option for HTML formating but that means that you have to write the breaks manually everytime you want to break the line.

It would be much more convenient to hit ENTER and it puts a line break not only in the editor but also in the view of the note.

It would be great if you could implement this into a future version.

Apart from that I love this add-on. Thanks again and please continue! Donated. 💸

**Comment by mlazdans** [comment]
Hello!

If you are referring formatting inside message you can pre-format notes using templating. You can find sample template to achieve word wrapping here: #47 Hope that is what you looking for.

**Comment by dompauling** [comment]
This is exactly what I was looking for. Thank you! 🤗

Is there some documentation where I can read more about templating?

**Comment by mlazdans** [comment]
No, there is no documentation at the moment. Only pieces I've written is [README](https://github.com/mlazdans/qnote) and [migration from XNote++ guide](https://github.com/mlazdans/qnote/blob/master/doc/migration-guide.md)

**Comment by mlazdans** [comment]
Related to #47
