### ISSUE TITLE
QNote does not disappear when changing to another email without QNote

### ISSUE THREAD

**Issue by KayLpz** [mlazdans/qnote#67]
Hello,
I was forced to update qnote to the newest version (TB128 ).
If I switch in inbox from a mail with qnote to another one without, the old qnote remains on the screen. Only if the new mail has a qnote too it switches to the newer one, than this qnote remains on the screen.
This results in the wrong note being assigned to another email.
Thank you for taking care
Regards Kay

**Comment by bogdandragomir** [comment]
Martins, please include an option to automatically close notes when switching from an email to another, as it was.

Thank you!
Bogdan

**Comment by mlazdans** [comment]
Will be fixed in next release

**Comment by mlazdans** [comment]
I published preview version, here #68
Please test it out
