### ISSUE TITLE
QNote version 0.14.3 Popup issue

### ISSUE THREAD

**Issue by pandyaph** [mlazdans/qnote#68]
Hi,
I am having issue with Popup of QNote in Thunderbird (Ver. 128.3.3esr (64-bit)).
QNote is attached is the email message but when we click on the message the Popup appears. The Popup remains on Laptop screen even if we minimize the Thunderbird. Even it remains open on any other application is open. I am sharing few screenshots of the same. When we click on Close and Save button on right side of Popup, it disappears.

Awaiting resolution from your end.
Regards,
Prashant

![Screenshot_1](https://github.com/user-attachments/assets/c2b1e88d-f799-48ad-ba44-83e3feb02d7b)
![Screenshot_2](https://github.com/user-attachments/assets/b322f8f6-3427-4f0e-9a16-3da8b16923e9)
![Screenshot_3](https://github.com/user-attachments/assets/7246ce96-8c46-4c84-8628-5b9a74c94ba4)

**Comment by Michelina1** [comment]
I am having the same issue. It started after updating Thunderbird to version 128.3.3esr (32-bit).

**Comment by pandyaph** [comment]
Awaiting update from Developer on this issue.

**Comment by mlazdans** [comment]
I probably will add checkbox to close notes automatically. At this moment it is users responsibility to close it when fit. Popup window is not that well supported. Did you tried floating panel?
![image](https://github.com/user-attachments/assets/cf67c519-2fdc-4da6-98fc-a5be0188b353)

**Comment by pandyaph** [comment]
I tried Floating Panel. But still Popups are attached with other emails in which there is no QNote attached but Popup has stopped appearing on desktop and other screens now.

**Comment by DenB10** [comment]
Hi,
I agree that this is a bug that didn't occur with earlier versions.

@mlazdans 
I pointed it out, along with other anomalies, in an e-mail I sent you about three weeks ago, but perhaps you didn't receive it?

**Comment by mlazdans** [comment]
Not just yet :|

**Comment by mlazdans** [comment]
Will be fixed in next release

**Comment by mlazdans** [comment]
Feel free to test preview version and report issues: 
[qnote-0.14.4pre1.zip](https://github.com/user-attachments/files/18048198/qnote-0.14.4pre1.zip)

This should revert close and save behaviour as it was pre 0.14.x versions.

**Comment by pandyaph** [comment]
> Feel free to test preview version and report issues: [qnote-0.14.4pre1.zip](https://github.com/user-attachments/files/18048198/qnote-0.14.4pre1.zip)
> 
> This should revert close and save behaviour as it was pre 0.14.x versions.

Seems the issue is resolved. Thanks for the resolution
