### ISSUE TITLE
Context menu does not appear or work in page context with QNote 0.14.3

### ISSUE THREAD

**Issue by DenB10** [mlazdans/qnote#71]
Hi,
I managed to test QNote 0.14 on a Windows 10 virtual machine (Remember that I have Windows7 on my computer and cannot install TB 128 on it).
The QNote menu works very well in the "message_list" context but it doesn't appear in the "page" context as expected, or if it does appear from time to time, it doesn't work.
Can you reproduce?

**Comment by mlazdans** [comment]
Hi! What you mean by page context? Please report steps taken and also some screenshots would help. Thanks!

**Comment by DenB10** [comment]
In the “Menu.mjs” module, you have defined three contexts for the context menu: “message_list”, “page” and “frame”. However, the QNote menu only appears in the “message_list” context, i.e. when you right-click on a message in the message list. However, if you right-click in the body of the message (“page” context), it does not appear.

**Comment by DenB10** [comment]
Some screenshots:

1. Right-click on a message in the list: the QNote menu appears
![sc1](https://github.com/user-attachments/assets/001c921b-a384-4c4d-9394-78096b597327)

2. Right-click on the body of a message: the QNote menu doesn't appear
![sc2](https://github.com/user-attachments/assets/50cc3667-d079-4c5b-91cb-ad1b7b6070ac)

**Comment by mlazdans** [comment]
OK I see. Will fix it with next release.
