### ISSUE TITLE
Qnote Icon to large when opening Inbox or saved searches via content menu -> Open in New Tab

### ISSUE THREAD

**Issue by mariocup** [mlazdans/qnote#72]
If I use the QNote Icon in the column view of TB 128.5.1 it works fine if only one Tab is open.

If I try to use the context menu Open in New Tab the QNote Icon is to large and will result that the line spaces between different emails because very big. I am using the Vertical View settings.

**Comment by mlazdans** [comment]
Any screenshots?

**Comment by mariocup** [comment]
Here you see how it appears under the new Tab with and without enabled QNote column.
![with_qnote](https://github.com/user-attachments/assets/e5322a0e-da52-4776-b045-fb5239b0adc7)
![without_qnote](https://github.com/user-attachments/assets/bfdbf9cb-64de-4e23-b58c-1cbe51f002fb)

This problem only appears if you open in a New Tab. In the normal view (Standard Tab) everything works without issues even if the Qnote column is enabled.

**Comment by mlazdans** [comment]
Will be fixed with next release
