### ISSUE TITLE
Feature Request: Option to add QText Column in Search Message Dialog

### ISSUE THREAD

**Issue by mariocup** [mlazdans/qnote#73]
Thunderbird provides the possibility to search via the menu Edit->Find->Search Messages. Here you can specify conditions like
QNote contains a search pattern
Age in Days less than 120

Right now in the search result view it is not possible to show the QText as Column which would be really helpful.

The workaround is to save the Search Result via the button "Save as Search Folder". In the Saved Search Folder I can add the Column QText. The Saved Search Folder allows you also to select in the Properties which Email Folder should be included in the Search e.g. Inbox or other folders.

The saved searched Folder is pretty slow if you switch between different Folders as every time you switch it takes minutes to refresh.

The Edit->Find->Search Message is fast and can be used as floating window. Therefore having the possibility to add the QText column would be very nice.

Really cool would be also to have the possibility to edit the QText via Shortcut or Context Menu in the Results View of Search Message.

**Comment by mlazdans** [comment]
Missing column for add-ons on search results is shortcoming of recent changes to the TB API. Before 115 it worked just fine. I'm pretty sure TB developers are aware of this but if not, then you can open a bug report with TB.

Regarding context menu in search results I have to investigate it a bit more. Right now missing context menu altogether indicates to me it might be impossible at the moment.

**Comment by mlazdans** [comment]
Both of these features can't be implemented at the moment. At least with no simple solution.
