### ISSUE TITLE
Keyboard shortcut to save and close note?

### ISSUE THREAD

**Issue by nickwynja** [mlazdans/qnote#74]
Really liking the extension so far. I can't find anything in the docs or code but is there a keyboard shortcut to save and close a note? I've tried common combinations like command+enter with no success.

**Comment by mlazdans** [comment]
Not sure where did you try to find about usage. It's on both places 

https://github.com/mlazdans/qnote
![image](https://github.com/user-attachments/assets/7f07cfb0-27b8-4275-9e74-7d4d3b4adfac)
https://addons.thunderbird.net/en-US/thunderbird/addon/qnote/
![image](https://github.com/user-attachments/assets/afafe5c0-062a-4c5a-b720-cde9623ec207)

**Comment by mlazdans** [comment]
I do not understand how would Esc be more natural for saving? Everywhere else Esc is used to just CLOSE something, to escape from something. This would break common esc usage conventions. Won't do it, sorry.

**Comment by nickwynja** [comment]
> If you select the TB menu Tools->Add-ons and Themes you see the cogwheel button. Then select the context menu: Manage Extension Shortcut. Afterwards customize the shortcut for Toggle the QNote.

@mariocup Thanks, I had already customized the shortcut to ctrl-n which opened the note but did not close it.

@mlazdans When I reset the shortcut back to alt-q, the command worked to open and close. I tested out a few configurations and it looks like the customized shortcut only works to open QNote but no matter what you set the shortcut to only Alt-Q saves/closes it. Is this expected behavior?

As for the usage, I read "toggle" as show/hide and not that it applied to opening and also saving+closing.

**Comment by mlazdans** [comment]
Currently indeed add-on does not respect user configured shortcut key on close. Will try to fix it. Probably will update readme as well to me more specific. Thanks!

**Comment by mlazdans** [comment]
I tried changing short cut key and actually new shortcut opens and also closes note correctly.

**Comment by nickwynja** [comment]
Seems this was specific to the Ctrl-N custom shortcut on mac. Must have been some conflict with other built-in command. Using Ctrl-Q here (instead of the default Alt-Q) did work to toggle.
