### ISSUE TITLE
QNote 0.14.4pre1 Test results

### ISSUE THREAD

**Issue by DenB10** [mlazdans/qnote#75]
Hi Martins,
Many thanks for fixing the bugs in version 0.14.3. This new version works very well now. However, I have two comments to make when notes are opened in a popup window:

1.  
![sc](https://github.com/user-attachments/assets/ace0fc4f-fdc0-480c-b0a1-f2f456707df5)

The two buttons I've circled in red do exactly the same thing, so there's one too many. In my opinion, the cross-shaped one is useless, as the window already has a close button.

2. I think it would be a good idea to keep the window in the foreground as with the floating panel, especially if you don't check the “auto close” option.

PS: I've updated the fr messages.json via PR

**Comment by mlazdans** [comment]
Regarding 2. I can not keep these windows on foreground. This is separate window which is controlled by OS and TB API does not expose any more controls.

**Comment by mlazdans** [comment]
Regarding 1. Extra title bar and controls will be removed in the next release.
